### ISSUE TITLE
Graphical bug on lower screen space

### ISSUE THREAD

**Issue by chroeseler** [NicolasGuilloux/blade-shadow-beta#12]
**Describe the bug**
When using shadow on linux my screen glitches on the lower 1/10 or so.
![grafics_bug](https://user-images.githubusercontent.com/4394840/47524360-b3542700-d89a-11e8-9763-e1184588375b.png)

I'm not confident that it's a issue with the AppImage, but rather with my x11 configuration. But up to now I don't have any clue where the problem originated.
When I use shadow in windowed mode the bug scales. So it is bound to the application window. 
![grafics_bug_windowed](https://user-images.githubusercontent.com/4394840/47525114-b94b0780-d89c-11e8-8865-b23f389d3fda.png)

**System**
 - OS: Arch
 - OS Version: 4.18.12-arch1-1-ARCH
 - Environment: awesome v4.2
 - Application: AppImage
 - Application Version: 2.0.2

**Configuration**
 - The user is in input group: Yes
 - The environment uses Xorg: Yes
 - VA API detects H264: Yes, H265: No

**To Reproduce**
1. Start Shadow Launcher with AppImage
2. Enjoy

**Comment by NicolasGuilloux** [comment]
You are not the only one to have this issue. It is linked with the VA API decoding functions.

I will recommand people with the same issue to publish in this issue and warn the developper about it.

In the meantime, can you post your `vainfo` please?

Thanks for reporting this bug.

**Comment by chroeseler** [comment]
Sure thing:

```
vainfo: VA-API version: 1.3 (libva 2.3.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Mobile - 2.2.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

**Comment by BurakDev** [comment]
Same for me.

I have a disabled GeForce 840m.

processor :
```Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz```

release :
```Ubuntu 18.04.1 LTS```

version :
```AppImage 2.0.2```

vainfo output :
```libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

**Comment by cedricboucard** [comment]
I have the same probleme 
![capture d ecran_2018-10-25_23-45-35](https://user-images.githubusercontent.com/43134785/47532331-4c416d00-d8b0-11e8-8e36-5a3ca0b8e020.png)
version : 

> AppImage 2.0.2

Vainfo output : 
```
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Desktop - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

**Comment by MouhK** [comment]
Hi !

Could you check your intel driver options (if any) in Xorg ?
Could you try this ?

- Create "/etc/X11/xorg.conf.d/shadow.conf"
- Add this Section

```
Section "Device"
        Identifier "Intel Graphics"
        Driver "intel"
        Option "AccelMethod" "sna"
        Option "DRI" "3"
        Option "TearFree" "True"
EndSection

```
- log out

This will load dri3, enable "sna" (default method).
The SNA acceleration method causes tearing on some machines, the "TearFree" option fix this.

**Comment by chroeseler** [comment]
I don't had any intel configs in my X11 folder.
I created this shadow.conf file like described and restarted my xorg session, but nothing changed.

**Comment by MouhK** [comment]
Could try to play this [video](https://drive.google.com/file/d/1nrx5LLPzNyidu9ishAw6WwXStq5HJ8sM/view?usp=sharing) with mpv (you probably need to install it).
`mpv  --vo=vaapi --hwdec=vaapi -v nature1080p-high.h264`

Make sure the log displays `[vd] Using hardware decoding (vaapi).`

If you have the same issue, it's probably linked to your environment, otherwise my code :)
This will help a lot.

Thank you !

**Comment by chroeseler** [comment]
Hey, played the video. No problems there. vaapi was used. 
I added the mpv output.
[h264.log](https://github.com/NicolasGuilloux/blade-shadow-beta/files/2526604/h264.log)
Hope that helps. :D

**Comment by MouhK** [comment]
Thanks a lot. This will help me fix it faster :)

**Comment by aarnoud** [comment]
@MouhK well, we tested many options (sna/uxa/triplebuffer/DRI) without success. HD2000-HD4000 still suffers the issue. Those card works on Windows and Mac, so it's not a GPU issue. I've tested it also against 2.0.0-b10, same issue.

**Comment by jpmlima** [comment]
did you solve the problem m8?

**Comment by Bulbyzarr** [comment]
Hello guys,

Actually, if i use the stable version of Appimage, the shadow is launched but i have a black screen but with the latest version, the shadow crashes.

I did the test with the video like explained in the previous message and this my result : 
https://pastebin.com/gUwSD4WN

Hardware Spec : 
- Archlinux on Laptop and Desktop
- AMD RX580 8Gb for the Desktop and RX Vega 8 (iGPU from Ryzen 2500U) for the laptop 

The both GPU are Classic consumers.

**Comment by NicolasGuilloux** [comment]
Hi guys !

Somebody found on his computer that increasing the bandwidth removes the bottom tearing. If your connection allows it, can you try ?
Moreover, the latest version of the application now uses OpenGL, if somebody with this bug can check if there is an improvement.

Thanks guys!

**Comment by Bulbyzarr** [comment]
The issue with AMD GPU on Linux will be not fixed one day ?
There is no one in the development team who can try to find where the problem comes from ?
It's not up to users to find where it comes from ...
Already it does not work with recent Nvidia cards on Linux / Windows. The usefulness of Shadow is really limited.

**Comment by NicolasGuilloux** [comment]
Hi,

This Github was not created to complain about the developpers but to help them collect bugs. I understand your frustration, but stay cool :)
I don't really now the state of the development regarding hardware support. 
Some Nvidia work on Linux with the Arekinath patch or the Nvidia firmware.
On Windows, a very large amount of hardware is supported as well.

**Comment by aarnoud** [comment]
for tracking purpose on an HD4400

![Screenshot_from_2019-03-02_05-13-56](https://user-images.githubusercontent.com/3198544/55740835-38d42980-5a2c-11e9-8c81-592ccf7f7ce8.png)

**Comment by aarnoud** [comment]
another one on Intel HD line :

![20181229_183442](https://user-images.githubusercontent.com/3198544/55742374-cd8c5680-5a2f-11e9-91d1-7b326df22ced.jpg)

**Comment by Distil62** [comment]
Hello,

I have the same issue and i don't know how to solve it
System informations :
```
OS: Ubuntu 18.04.2 LTS x86_64 
Host: HP ProBook 6560b A0001D02 
Kernel: 4.15.0-45-generic 
Uptime: 1 hour, 18 mins 
Packages: 1775 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Vimix-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i3-2310M (4) @ 2.100GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 2360MiB / 3878MiB
```

Vainfo output : 
```
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

mpv h264 test output
[h264-high.log](https://github.com/NicolasGuilloux/blade-shadow-beta/files/3103230/h264-high.log)

Shadow launcher settings :
50mb bandwith
h265 ON
Fullscreen at start
Auto-shutdown OFF
UDP protocol
Micro OFF

Runtime screenshot
![shadowScreen](https://user-images.githubusercontent.com/17656761/56498925-5614f780-6504-11e9-8e5f-ad349c46c953.png)


I hope this informations will help you :)
Thank for your job :+1:

**Comment by aarnoud** [comment]
if you can provide `LIBVA_TRACE=/tmp/shadow_va_trace.log ./ShadowBeta.AppImage` that could help

**Comment by prokopyl** [comment]
I have the same issue, Shadow is pretty much unusable on my laptop.

My system specs:

```Operating System: Arch Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3
Kernel Version: 5.0.9-arch1-1-ARCH
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-2450M CPU @ 2.50GHz
Memory: 15,6 Gio
```
Screenshot:
![image](https://user-images.githubusercontent.com/6529475/56856956-afe34a80-6966-11e9-8335-d5a44b9d9364.png)

Also attached is the libVA trace (I only left the Shadow running for a few seconds to generate this trace):
[shadow_va_trace.log.011752.thd-0x00004841.txt](https://github.com/NicolasGuilloux/blade-shadow-beta/files/3124507/shadow_va_trace.log.011752.thd-0x00004841.txt)

VA-API video decoding works fine on other applications (tested VLC and mpv here) on my system, there are no glitches nor other artifacts.

**Comment by fatelgit** [comment]
I can confirm this issue for me as well. 

![image](https://user-images.githubusercontent.com/13215733/57208205-dc384000-6fd2-11e9-8e67-adc342a6ce65.png)

Additional system information:
Intel i5-4300M with Intel HD4600 graphics
Ubuntu 18.04 LTS
Kernel 4.15.0-48-generic

Log attached. Please let me know if I can do anything else to trace the problem. 

[shadow_va_trace.log.054359.thd-0x00001fa1.log](https://github.com/NicolasGuilloux/blade-shadow-beta/files/3146607/shadow_va_trace.log.054359.thd-0x00001fa1.log)

**Comment by princeathane** [comment]
I'm having the same issues. However, in my case only happens when my camera is going at a high speed. Please fix this

**Comment by princeathane** [comment]
Here is what am I receiving:
<pre>libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 19.0.2 for AMD BONAIRE (DRM 2.50.0, 4.15.0-52-generic, LLVM 8.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileNone                   :	VAEntrypointVideoProc
</pre>

**Comment by aarnoud** [comment]
@princeathane this issue is only related to Intel HD cards, please create a new issue with as much details as possible, screenshot or video of the issue, and required details. thanks

**Comment by niksteff** [comment]
Hey guys,

got the same problem on Kubuntu 18.04.3 LTS with an Intel sandybrige HD GPU. Artifacts in the lower part of the screen. This is a macbook pro running kubuntu and the internal AMD GPU is deactivated => so its forced to run on the intel hd. Everything works on macOS (well mostly because it uses the AMD card). Seems to be related to the intel card. Is there something off with the buffer or the speed the buffer can be written to or something?

Can i provide some more details for you?

`
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
`

And here is the link to the system information file: https://nicolasguilloux.eu/hostbin/3464032691

And here is the log from the video from the top of the issue: No visible problems there. 
https://gist.github.com/dNvl/ef18ff36f7161c5c22cc4049cdd7a09c

**Comment by CrawX** [comment]
I'm facing the same issue described here running Archlinux on my late 2013 Macbook Pro (Intel Iris 5100). I did install the relevant vaapi drivers, vainfo shows h264 support and mpv plays 4k h264 flawlessly.
When running shadow (all available versions, beta or not) I'm seeing the same green areas and see huge cpu usage and input lag.
I'd be happy to provide additional information or try testbuilds. I just now saw that there was a way to get a vaapi trace, I'll check that later, the client doesn't seem to log a lot so there's not much room to tinker around with it myself...

**Comment by elineda** [comment]
Hello, 
I have the same problem with fedora 30 and intel driver

`
➜  ~ vainfo`
`libva info: VA-API version 1.4.1`
`libva info: va_getDriverName() returns 0`
`libva info: Trying to open /usr/lib64/dri/i965_drv_video.so`
`libva info: Found init function __vaDriverInit_1_4`
`/usr/lib64/dri/hybrid_drv_video.so init failed`
`Not using hybrid_drv_video.so`
`libva info: va_openDriver() returns 0`
`vainfo: VA-API version: 1.4 (libva 2.4.1)`
`vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Desktop - 2.3.0`
`vainfo: Supported profile and entrypoints`
`      VAProfileMPEG2Simple            : VAEntrypointVLD`
`      VAProfileMPEG2Main              : VAEntrypointVLD`
`      VAProfileH264ConstrainedBaseline: VAEntrypointVLD`
`      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice`
`      VAProfileH264Main               : VAEntrypointVLD`
`      VAProfileH264Main               : VAEntrypointEncSlice`
`      VAProfileH264High               : VAEntrypointVLD`
`      VAProfileH264High               : VAEntrypointEncSlice`
`      VAProfileH264StereoHigh         : VAEntrypointVLD`
`      VAProfileVC1Simple              : VAEntrypointVLD`
`      VAProfileVC1Main                : VAEntrypointVLD`
`      VAProfileVC1Advanced            : VAEntrypointVLD`
`      VAProfileNone                   : VAEntrypointVideoProc`

**Comment by erwanriou** [comment]
Hi Nicolas,

On this specific configuration i observe the same phenomene :
https://nicolasguilloux.eu/hostbin/3570447996

here a screen of how it looklike
![Capture d’écran de 2019-10-17 02-27-32](https://user-images.githubusercontent.com/30130006/66969183-e59cfc80-f088-11e9-96e7-337982059935.png)

**Comment by aarnoud** [comment]
> On this specific configuration i observe the same phenomene :
> https://nicolasguilloux.eu/hostbin/3570447996

Hi, looks like you are using an HD3000, so yes, it's the same issue, thanks for feedback!

**Comment by NicolasGuilloux** [comment]
Hi there
A patch is currently under development by Blade to fix that. Big up to them :)

We'll keep you update when it is released.

**Comment by NicolasGuilloux** [comment]
Hi there ! 
The patch is available on the Alpha channel (https://update.shadow.tech/launcher/testing/linux/ubuntu_18.04/ShadowAlpha.zip).

Please try to start the stream multiple times and make sure your `vainfo` returns positive information.

I will close this issue as it is solved. Nonetheless, if you still have the bug, send me your vainfo via Discord as your GPU may need to be added by Shadow on their whitelist.

Big up to @MouhK who found the issue :)

**Comment by hkramski** [comment]
I still have this bug on Arch Linux, even with the Alpha client. Hardware is Intel® Core™ i5-4200U CPU @ 1.60GHz Mesa DRI Intel® HD Graphics 4400, 

Don't know where to post on Discord, so I post it here:
```
vainfo: VA-API version: 1.8 (libva 2.7.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
```
TIA
   Heinz

**Comment by opie4624** [comment]
I'm also getting this issue on Alpha and Beta.

```
vainfo: VA-API version: 1.8 (libva 2.8.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

ArchLinux, Gnome running on X11 (not wayland), Core i7-3537U, with Intel HD4000 graphics

**Comment by gtxaspec** [comment]
Same issue,  Corrupted screen, sometimes the entire screen, sometimes the lower half, sometimes freezes xorg.

ThinkPad x230 i7-3520M
OS: Ubuntu 20.04 Mate
Shadow: Stable/Beta/Alpha ( all have issue )
X11

This issue has been occurring since Ubuntu 19.  Curiously, when Shadow is run using an Ubuntu 18.04 chroot (which is what led me to create [shadowroot](https://github.com/gtxaspec/shadowroot) the issue doesn't occur and Shadow works perfectly.

Software Rendering naturally works in alpha, though a bit laggy.

```
$ vainfo
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.8.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

**Comment by NicolasGuilloux** [comment]
I can see that the `iHD` driver failed to initialize. Did you installed [intel-media-va-driver-non-free](https://packages.ubuntu.com/search?keywords=intel-media-va-driver-non-free)? 

Moreover, this is a closed issue because the original problem was fixed, or at least the Shadowdocker workaround was pointed out. Do you mind creating a new issue if you still think you still need assistance? Cheers :)
